### PR TITLE
Tweet for github eda notebook

### PR DESCRIPTION
**Pull request by MichaelClifford**
https://github.com/aicoe-aiops/ocp-ci-analysis/issues/304

### CODE REVIEW

**Comment by MichaelClifford** [comment]
cc @oindrillac

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Review by oindrillac — COMMENTED** [review]
/approve
/hold

**Pull request merged**
