### PR TITLE
added tweeting instructions to readme

### PR DESCRIPTION
**Pull request by oindrillac**
updated readme with more context on the process

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
/lgtm
sesheta didn't have access to this repo, testing

**Comment by tumido** [comment]
@oindrillac what are you trying to retest? Pre-commit? We haven't set that up yet... I'll create a PR.

**Comment by tumido** [comment]
@oindrillac https://github.com/operate-first/operate-first-twitter/pull/9 seems to be helping

**Comment by oindrillac** [comment]
@tumido just re-testing tide. It was previously giving a tide error like "merge type squash disallowed by repo settings".
hence, I went in and checked the box which allows auto-merges.
and now it seems to not throw that error anymore

**Comment by tumido** [comment]
ahh.. interesing :slightly_smiling_face: I never seen that message... Maybe we can take a look once the PR is merged what merge strategy prow uses and tune it in the settings for this repo.. :slightly_smiling_face:

**Review by tumido — APPROVED** [review]
/approve

**Comment by oindrillac** [comment]
yes! basically this needs to be checked by default i think

image

**Review by HumairAK — APPROVED** [review]

**Pull request merged**
