### PR TITLE
chore: test prow's /approve

### PR DESCRIPTION
**Pull request by tumido**
This is a PR trying to create a reproducer for `approve` label not being cleared after a PR push (https://github.com/operate-first/operate-first-twitter/pull/7#event-4657168525). Please don't touch this PR. It might get merged - I'll revert it if that's the case. Sorry for abusing this repo. 

Plan:
1. I hold this PR
2. I `/lgtm` it
3. I `/approve` it
4. I push to this PR
5. At this stage, the `lgtm` label will be cleared, the `approve` will stay (which is the problem)
6. I unhold it
7. I hope it doesn't get merged. If it does, we have a problem

### CODE REVIEW

**Comment by tumido** [comment]
/lgtm
?

**Comment by tumido** [comment]
I'll wait for somebody help me to lgtm this to have a full reproducer

**Comment by goern** [comment]
I'm pretty sure this test will fail, as it is testing for the negated feature of prow, an approval needs to be removed manually.

maybe your test is covered by https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approve_test.go ?

**Comment by tumido** [comment]
:bomb: :boom:

**Pull request merged**
