### PR TITLE
Kelsey Hightower - @projectsigstore is extra dope

### PR DESCRIPTION
**Pull request by schwesig**
Kelsey Hightower - @projectsigstore is extra dope

gChat OCTO-ET mentioned a tweet by Kelsey Hightower and that he loves sigstore (besides other things from Red Hat). what a great acknowledgement.
I need to share this....

I gotta say,
@projectsigstore
 is extra dope. This is what modern software signing and verification looks like.

It's been 15 years since I was blown away by
@RedHat's end to end packaging solution, 👋 RPM and Yum, and this is looking real familiar. https://sigstore.dev

https://www.redhat.com/en/blog/sigstore-open-answer-software-supply-chain-trust-and-security

### CODE REVIEW

**Comment by oindrillac** [comment]
/lgtm 👍 
/hold
@schwesig do you want to retweet with a quote instead? Can share creds with you

**Comment by schwesig** [comment]
@oindrillac Please change and do what is needed. Quick here was the plan. Not perfect. Octo channel is wondering why social media takes us so long, I wanted to proof them wrong.

**Comment by schwesig** [comment]
BTW
If sharing cress is the only solution for this, we must find another solution in my opinion.

**Comment by oindrillac** [comment]
Done, here it is https://twitter.com/OperateFirst/status/1502407947749576706
closing this @schwesig :)

**Comment by schwesig** [comment]
@oindrillac great tweet, thank you for making it look way better than my draft version 👏

**Pull request closed without merging**
