### PR TITLE
Create S01E06espresso.tweet

### PR DESCRIPTION
**Pull request by isabelizimm**

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
how about tagging @pacospace's 🐦  `@paco_space` instead of name?

**Review by oindrillac — APPROVED** [review]
/lgtm 💯 
/approve

**Comment by oindrillac** [comment]
/hold 
until tomorrow :)

**Comment by oindrillac** [comment]
@isabelizimm I think we need to remove the trailing whitespace to fix the pre-commit

**Comment by isabelizimm** [comment]
> @isabelizimm I think we need to remove the trailing whitespace to fix the pre-commit

Updated!

**Pull request merged**
